//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiousEPortal.EPortalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EPortalService.ILoginService")]
    public interface ILoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetMenus", ReplyAction="http://tempuri.org/ILoginService/GetMenusResponse")]
        EPortalModel.T_ADMM_FuncList[] GetMenus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetMenus", ReplyAction="http://tempuri.org/ILoginService/GetMenusResponse")]
        System.Threading.Tasks.Task<EPortalModel.T_ADMM_FuncList[]> GetMenusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/UsrVal", ReplyAction="http://tempuri.org/ILoginService/UsrValResponse")]
        int UsrVal(string UsrID, string PassWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/UsrVal", ReplyAction="http://tempuri.org/ILoginService/UsrValResponse")]
        System.Threading.Tasks.Task<int> UsrValAsync(string UsrID, string PassWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetSupperUsr", ReplyAction="http://tempuri.org/ILoginService/GetSupperUsrResponse")]
        string GetSupperUsr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetSupperUsr", ReplyAction="http://tempuri.org/ILoginService/GetSupperUsrResponse")]
        System.Threading.Tasks.Task<string> GetSupperUsrAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetUsrByUsrID", ReplyAction="http://tempuri.org/ILoginService/GetUsrByUsrIDResponse")]
        EPortalModel.T_ADMM_UsrMst GetUsrByUsrID(string UsrID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetUsrByUsrID", ReplyAction="http://tempuri.org/ILoginService/GetUsrByUsrIDResponse")]
        System.Threading.Tasks.Task<EPortalModel.T_ADMM_UsrMst> GetUsrByUsrIDAsync(string UsrID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : DiousEPortal.EPortalService.ILoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<DiousEPortal.EPortalService.ILoginService>, DiousEPortal.EPortalService.ILoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EPortalModel.T_ADMM_FuncList[] GetMenus() {
            return base.Channel.GetMenus();
        }
        
        public System.Threading.Tasks.Task<EPortalModel.T_ADMM_FuncList[]> GetMenusAsync() {
            return base.Channel.GetMenusAsync();
        }
        
        public int UsrVal(string UsrID, string PassWord) {
            return base.Channel.UsrVal(UsrID, PassWord);
        }
        
        public System.Threading.Tasks.Task<int> UsrValAsync(string UsrID, string PassWord) {
            return base.Channel.UsrValAsync(UsrID, PassWord);
        }
        
        public string GetSupperUsr() {
            return base.Channel.GetSupperUsr();
        }
        
        public System.Threading.Tasks.Task<string> GetSupperUsrAsync() {
            return base.Channel.GetSupperUsrAsync();
        }
        
        public EPortalModel.T_ADMM_UsrMst GetUsrByUsrID(string UsrID) {
            return base.Channel.GetUsrByUsrID(UsrID);
        }
        
        public System.Threading.Tasks.Task<EPortalModel.T_ADMM_UsrMst> GetUsrByUsrIDAsync(string UsrID) {
            return base.Channel.GetUsrByUsrIDAsync(UsrID);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EPortalService.IUsrGroupService")]
    public interface IUsrGroupService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsrGroupService/GetUsrGrpsToChCol", ReplyAction="http://tempuri.org/IUsrGroupService/GetUsrGrpsToChColResponse")]
        string GetUsrGrpsToChCol(string TempTabNam, string IfGetFstRow, string FltSQL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsrGroupService/GetUsrGrpsToChCol", ReplyAction="http://tempuri.org/IUsrGroupService/GetUsrGrpsToChColResponse")]
        System.Threading.Tasks.Task<string> GetUsrGrpsToChColAsync(string TempTabNam, string IfGetFstRow, string FltSQL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsrGroupService/GetGrpUsrsByGrpCodeToChCol", ReplyAction="http://tempuri.org/IUsrGroupService/GetGrpUsrsByGrpCodeToChColResponse")]
        string GetGrpUsrsByGrpCodeToChCol(string TempTabNam, string GrpCode, string IfGetFstRow, string PanelNam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsrGroupService/GetGrpUsrsByGrpCodeToChCol", ReplyAction="http://tempuri.org/IUsrGroupService/GetGrpUsrsByGrpCodeToChColResponse")]
        System.Threading.Tasks.Task<string> GetGrpUsrsByGrpCodeToChColAsync(string TempTabNam, string GrpCode, string IfGetFstRow, string PanelNam);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsrGroupServiceChannel : DiousEPortal.EPortalService.IUsrGroupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsrGroupServiceClient : System.ServiceModel.ClientBase<DiousEPortal.EPortalService.IUsrGroupService>, DiousEPortal.EPortalService.IUsrGroupService {
        
        public UsrGroupServiceClient() {
        }
        
        public UsrGroupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsrGroupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsrGroupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsrGroupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetUsrGrpsToChCol(string TempTabNam, string IfGetFstRow, string FltSQL) {
            return base.Channel.GetUsrGrpsToChCol(TempTabNam, IfGetFstRow, FltSQL);
        }
        
        public System.Threading.Tasks.Task<string> GetUsrGrpsToChColAsync(string TempTabNam, string IfGetFstRow, string FltSQL) {
            return base.Channel.GetUsrGrpsToChColAsync(TempTabNam, IfGetFstRow, FltSQL);
        }
        
        public string GetGrpUsrsByGrpCodeToChCol(string TempTabNam, string GrpCode, string IfGetFstRow, string PanelNam) {
            return base.Channel.GetGrpUsrsByGrpCodeToChCol(TempTabNam, GrpCode, IfGetFstRow, PanelNam);
        }
        
        public System.Threading.Tasks.Task<string> GetGrpUsrsByGrpCodeToChColAsync(string TempTabNam, string GrpCode, string IfGetFstRow, string PanelNam) {
            return base.Channel.GetGrpUsrsByGrpCodeToChColAsync(TempTabNam, GrpCode, IfGetFstRow, PanelNam);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EPortalService.ICommon")]
    public interface ICommon {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/SetCurUsrInfo", ReplyAction="http://tempuri.org/ICommon/SetCurUsrInfoResponse")]
        void SetCurUsrInfo(string CurUsrID, string CurUsrName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/SetCurUsrInfo", ReplyAction="http://tempuri.org/ICommon/SetCurUsrInfoResponse")]
        System.Threading.Tasks.Task SetCurUsrInfoAsync(string CurUsrID, string CurUsrName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/SaveData", ReplyAction="http://tempuri.org/ICommon/SaveDataResponse")]
        void SaveData(string StrXML, string SQL, EPortalCommom.OperType operType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/SaveData", ReplyAction="http://tempuri.org/ICommon/SaveDataResponse")]
        System.Threading.Tasks.Task SaveDataAsync(string StrXML, string SQL, EPortalCommom.OperType operType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/SaveData1", ReplyAction="http://tempuri.org/ICommon/SaveData1Response")]
        void SaveData1(string StrXML, string SQL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/SaveData1", ReplyAction="http://tempuri.org/ICommon/SaveData1Response")]
        System.Threading.Tasks.Task SaveData1Async(string StrXML, string SQL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/RepeatCheck", ReplyAction="http://tempuri.org/ICommon/RepeatCheckResponse")]
        int RepeatCheck(string TabName, string PrimaryKey, string KeyValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/RepeatCheck", ReplyAction="http://tempuri.org/ICommon/RepeatCheckResponse")]
        System.Threading.Tasks.Task<int> RepeatCheckAsync(string TabName, string PrimaryKey, string KeyValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetChColByEnCol", ReplyAction="http://tempuri.org/ICommon/GetChColByEnColResponse")]
        string GetChColByEnCol(string TabNam, string EnColNam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetChColByEnCol", ReplyAction="http://tempuri.org/ICommon/GetChColByEnColResponse")]
        System.Threading.Tasks.Task<string> GetChColByEnColAsync(string TabNam, string EnColNam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetColsByPanelNam", ReplyAction="http://tempuri.org/ICommon/GetColsByPanelNamResponse")]
        string GetColsByPanelNam(string PanelNam, string FrmNam, string TabNam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetColsByPanelNam", ReplyAction="http://tempuri.org/ICommon/GetColsByPanelNamResponse")]
        System.Threading.Tasks.Task<string> GetColsByPanelNamAsync(string PanelNam, string FrmNam, string TabNam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetFltColsByPanelNam", ReplyAction="http://tempuri.org/ICommon/GetFltColsByPanelNamResponse")]
        string GetFltColsByPanelNam(string PanelNam, string FrmNam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetFltColsByPanelNam", ReplyAction="http://tempuri.org/ICommon/GetFltColsByPanelNamResponse")]
        System.Threading.Tasks.Task<string> GetFltColsByPanelNamAsync(string PanelNam, string FrmNam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetTabStrc", ReplyAction="http://tempuri.org/ICommon/GetTabStrcResponse")]
        string GetTabStrc(string TabNam, string FrmNam, EPortalCommom.OperType operType, string KeyWords, string PanelNam, string CurUsrID, string CurUsrName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetTabStrc", ReplyAction="http://tempuri.org/ICommon/GetTabStrcResponse")]
        System.Threading.Tasks.Task<string> GetTabStrcAsync(string TabNam, string FrmNam, EPortalCommom.OperType operType, string KeyWords, string PanelNam, string CurUsrID, string CurUsrName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetTabByFrmNam", ReplyAction="http://tempuri.org/ICommon/GetTabByFrmNamResponse")]
        string GetTabByFrmNam(string FrmNam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetTabByFrmNam", ReplyAction="http://tempuri.org/ICommon/GetTabByFrmNamResponse")]
        System.Threading.Tasks.Task<string> GetTabByFrmNamAsync(string FrmNam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetFltSlt", ReplyAction="http://tempuri.org/ICommon/GetFltSltResponse")]
        string GetFltSlt(string UsrID, string FrmNam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetFltSlt", ReplyAction="http://tempuri.org/ICommon/GetFltSltResponse")]
        System.Threading.Tasks.Task<string> GetFltSltAsync(string UsrID, string FrmNam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/AddPrtFltSlt", ReplyAction="http://tempuri.org/ICommon/AddPrtFltSltResponse")]
        int AddPrtFltSlt(string CurUsrID, string SltName, string FrmName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/AddPrtFltSlt", ReplyAction="http://tempuri.org/ICommon/AddPrtFltSltResponse")]
        System.Threading.Tasks.Task<int> AddPrtFltSltAsync(string CurUsrID, string SltName, string FrmName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/AddShFltSlt", ReplyAction="http://tempuri.org/ICommon/AddShFltSltResponse")]
        int AddShFltSlt(string UsrID, string SltName, string FrmName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/AddShFltSlt", ReplyAction="http://tempuri.org/ICommon/AddShFltSltResponse")]
        System.Threading.Tasks.Task<int> AddShFltSltAsync(string UsrID, string SltName, string FrmName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/DelFltSlt", ReplyAction="http://tempuri.org/ICommon/DelFltSltResponse")]
        int DelFltSlt(string SltName, string FrmName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/DelFltSlt", ReplyAction="http://tempuri.org/ICommon/DelFltSltResponse")]
        System.Threading.Tasks.Task<int> DelFltSltAsync(string SltName, string FrmName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/CheckIfUsrSlt", ReplyAction="http://tempuri.org/ICommon/CheckIfUsrSltResponse")]
        int CheckIfUsrSlt(string SltName, string UsrID, string FrmName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/CheckIfUsrSlt", ReplyAction="http://tempuri.org/ICommon/CheckIfUsrSltResponse")]
        System.Threading.Tasks.Task<int> CheckIfUsrSltAsync(string SltName, string UsrID, string FrmName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/EditFltSlt", ReplyAction="http://tempuri.org/ICommon/EditFltSltResponse")]
        int EditFltSlt(string SltName, string SltID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/EditFltSlt", ReplyAction="http://tempuri.org/ICommon/EditFltSltResponse")]
        System.Threading.Tasks.Task<int> EditFltSltAsync(string SltName, string SltID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/SaveFltSlt", ReplyAction="http://tempuri.org/ICommon/SaveFltSltResponse")]
        void SaveFltSlt(EPortalCommom.OperType operType, string StrXML, string TabName, string KeyWords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/SaveFltSlt", ReplyAction="http://tempuri.org/ICommon/SaveFltSltResponse")]
        System.Threading.Tasks.Task SaveFltSltAsync(EPortalCommom.OperType operType, string StrXML, string TabName, string KeyWords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetMaxSltID", ReplyAction="http://tempuri.org/ICommon/GetMaxSltIDResponse")]
        string GetMaxSltID(string FrmName, string SltType, string ParentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetMaxSltID", ReplyAction="http://tempuri.org/ICommon/GetMaxSltIDResponse")]
        System.Threading.Tasks.Task<string> GetMaxSltIDAsync(string FrmName, string SltType, string ParentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetFltSltDtlBySltID", ReplyAction="http://tempuri.org/ICommon/GetFltSltDtlBySltIDResponse")]
        string GetFltSltDtlBySltID(string SltID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetFltSltDtlBySltID", ReplyAction="http://tempuri.org/ICommon/GetFltSltDtlBySltIDResponse")]
        System.Threading.Tasks.Task<string> GetFltSltDtlBySltIDAsync(string SltID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/BeginTransaction", ReplyAction="http://tempuri.org/ICommon/BeginTransactionResponse")]
        void BeginTransaction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/BeginTransaction", ReplyAction="http://tempuri.org/ICommon/BeginTransactionResponse")]
        System.Threading.Tasks.Task BeginTransactionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/CommitTransaction", ReplyAction="http://tempuri.org/ICommon/CommitTransactionResponse")]
        void CommitTransaction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/CommitTransaction", ReplyAction="http://tempuri.org/ICommon/CommitTransactionResponse")]
        System.Threading.Tasks.Task CommitTransactionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/SaveFltSlt1", ReplyAction="http://tempuri.org/ICommon/SaveFltSlt1Response")]
        void SaveFltSlt1(EPortalCommom.OperType operType, string StrXML, string TabName, string KeyWords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/SaveFltSlt1", ReplyAction="http://tempuri.org/ICommon/SaveFltSlt1Response")]
        System.Threading.Tasks.Task SaveFltSlt1Async(EPortalCommom.OperType operType, string StrXML, string TabName, string KeyWords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/CloseSqlCon", ReplyAction="http://tempuri.org/ICommon/CloseSqlConResponse")]
        void CloseSqlCon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/CloseSqlCon", ReplyAction="http://tempuri.org/ICommon/CloseSqlConResponse")]
        System.Threading.Tasks.Task CloseSqlConAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonChannel : DiousEPortal.EPortalService.ICommon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonClient : System.ServiceModel.ClientBase<DiousEPortal.EPortalService.ICommon>, DiousEPortal.EPortalService.ICommon {
        
        public CommonClient() {
        }
        
        public CommonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetCurUsrInfo(string CurUsrID, string CurUsrName) {
            base.Channel.SetCurUsrInfo(CurUsrID, CurUsrName);
        }
        
        public System.Threading.Tasks.Task SetCurUsrInfoAsync(string CurUsrID, string CurUsrName) {
            return base.Channel.SetCurUsrInfoAsync(CurUsrID, CurUsrName);
        }
        
        public void SaveData(string StrXML, string SQL, EPortalCommom.OperType operType) {
            base.Channel.SaveData(StrXML, SQL, operType);
        }
        
        public System.Threading.Tasks.Task SaveDataAsync(string StrXML, string SQL, EPortalCommom.OperType operType) {
            return base.Channel.SaveDataAsync(StrXML, SQL, operType);
        }
        
        public void SaveData1(string StrXML, string SQL) {
            base.Channel.SaveData1(StrXML, SQL);
        }
        
        public System.Threading.Tasks.Task SaveData1Async(string StrXML, string SQL) {
            return base.Channel.SaveData1Async(StrXML, SQL);
        }
        
        public int RepeatCheck(string TabName, string PrimaryKey, string KeyValue) {
            return base.Channel.RepeatCheck(TabName, PrimaryKey, KeyValue);
        }
        
        public System.Threading.Tasks.Task<int> RepeatCheckAsync(string TabName, string PrimaryKey, string KeyValue) {
            return base.Channel.RepeatCheckAsync(TabName, PrimaryKey, KeyValue);
        }
        
        public string GetChColByEnCol(string TabNam, string EnColNam) {
            return base.Channel.GetChColByEnCol(TabNam, EnColNam);
        }
        
        public System.Threading.Tasks.Task<string> GetChColByEnColAsync(string TabNam, string EnColNam) {
            return base.Channel.GetChColByEnColAsync(TabNam, EnColNam);
        }
        
        public string GetColsByPanelNam(string PanelNam, string FrmNam, string TabNam) {
            return base.Channel.GetColsByPanelNam(PanelNam, FrmNam, TabNam);
        }
        
        public System.Threading.Tasks.Task<string> GetColsByPanelNamAsync(string PanelNam, string FrmNam, string TabNam) {
            return base.Channel.GetColsByPanelNamAsync(PanelNam, FrmNam, TabNam);
        }
        
        public string GetFltColsByPanelNam(string PanelNam, string FrmNam) {
            return base.Channel.GetFltColsByPanelNam(PanelNam, FrmNam);
        }
        
        public System.Threading.Tasks.Task<string> GetFltColsByPanelNamAsync(string PanelNam, string FrmNam) {
            return base.Channel.GetFltColsByPanelNamAsync(PanelNam, FrmNam);
        }
        
        public string GetTabStrc(string TabNam, string FrmNam, EPortalCommom.OperType operType, string KeyWords, string PanelNam, string CurUsrID, string CurUsrName) {
            return base.Channel.GetTabStrc(TabNam, FrmNam, operType, KeyWords, PanelNam, CurUsrID, CurUsrName);
        }
        
        public System.Threading.Tasks.Task<string> GetTabStrcAsync(string TabNam, string FrmNam, EPortalCommom.OperType operType, string KeyWords, string PanelNam, string CurUsrID, string CurUsrName) {
            return base.Channel.GetTabStrcAsync(TabNam, FrmNam, operType, KeyWords, PanelNam, CurUsrID, CurUsrName);
        }
        
        public string GetTabByFrmNam(string FrmNam) {
            return base.Channel.GetTabByFrmNam(FrmNam);
        }
        
        public System.Threading.Tasks.Task<string> GetTabByFrmNamAsync(string FrmNam) {
            return base.Channel.GetTabByFrmNamAsync(FrmNam);
        }
        
        public string GetFltSlt(string UsrID, string FrmNam) {
            return base.Channel.GetFltSlt(UsrID, FrmNam);
        }
        
        public System.Threading.Tasks.Task<string> GetFltSltAsync(string UsrID, string FrmNam) {
            return base.Channel.GetFltSltAsync(UsrID, FrmNam);
        }
        
        public int AddPrtFltSlt(string CurUsrID, string SltName, string FrmName) {
            return base.Channel.AddPrtFltSlt(CurUsrID, SltName, FrmName);
        }
        
        public System.Threading.Tasks.Task<int> AddPrtFltSltAsync(string CurUsrID, string SltName, string FrmName) {
            return base.Channel.AddPrtFltSltAsync(CurUsrID, SltName, FrmName);
        }
        
        public int AddShFltSlt(string UsrID, string SltName, string FrmName) {
            return base.Channel.AddShFltSlt(UsrID, SltName, FrmName);
        }
        
        public System.Threading.Tasks.Task<int> AddShFltSltAsync(string UsrID, string SltName, string FrmName) {
            return base.Channel.AddShFltSltAsync(UsrID, SltName, FrmName);
        }
        
        public int DelFltSlt(string SltName, string FrmName) {
            return base.Channel.DelFltSlt(SltName, FrmName);
        }
        
        public System.Threading.Tasks.Task<int> DelFltSltAsync(string SltName, string FrmName) {
            return base.Channel.DelFltSltAsync(SltName, FrmName);
        }
        
        public int CheckIfUsrSlt(string SltName, string UsrID, string FrmName) {
            return base.Channel.CheckIfUsrSlt(SltName, UsrID, FrmName);
        }
        
        public System.Threading.Tasks.Task<int> CheckIfUsrSltAsync(string SltName, string UsrID, string FrmName) {
            return base.Channel.CheckIfUsrSltAsync(SltName, UsrID, FrmName);
        }
        
        public int EditFltSlt(string SltName, string SltID) {
            return base.Channel.EditFltSlt(SltName, SltID);
        }
        
        public System.Threading.Tasks.Task<int> EditFltSltAsync(string SltName, string SltID) {
            return base.Channel.EditFltSltAsync(SltName, SltID);
        }
        
        public void SaveFltSlt(EPortalCommom.OperType operType, string StrXML, string TabName, string KeyWords) {
            base.Channel.SaveFltSlt(operType, StrXML, TabName, KeyWords);
        }
        
        public System.Threading.Tasks.Task SaveFltSltAsync(EPortalCommom.OperType operType, string StrXML, string TabName, string KeyWords) {
            return base.Channel.SaveFltSltAsync(operType, StrXML, TabName, KeyWords);
        }
        
        public string GetMaxSltID(string FrmName, string SltType, string ParentID) {
            return base.Channel.GetMaxSltID(FrmName, SltType, ParentID);
        }
        
        public System.Threading.Tasks.Task<string> GetMaxSltIDAsync(string FrmName, string SltType, string ParentID) {
            return base.Channel.GetMaxSltIDAsync(FrmName, SltType, ParentID);
        }
        
        public string GetFltSltDtlBySltID(string SltID) {
            return base.Channel.GetFltSltDtlBySltID(SltID);
        }
        
        public System.Threading.Tasks.Task<string> GetFltSltDtlBySltIDAsync(string SltID) {
            return base.Channel.GetFltSltDtlBySltIDAsync(SltID);
        }
        
        public void BeginTransaction() {
            base.Channel.BeginTransaction();
        }
        
        public System.Threading.Tasks.Task BeginTransactionAsync() {
            return base.Channel.BeginTransactionAsync();
        }
        
        public void CommitTransaction() {
            base.Channel.CommitTransaction();
        }
        
        public System.Threading.Tasks.Task CommitTransactionAsync() {
            return base.Channel.CommitTransactionAsync();
        }
        
        public void SaveFltSlt1(EPortalCommom.OperType operType, string StrXML, string TabName, string KeyWords) {
            base.Channel.SaveFltSlt1(operType, StrXML, TabName, KeyWords);
        }
        
        public System.Threading.Tasks.Task SaveFltSlt1Async(EPortalCommom.OperType operType, string StrXML, string TabName, string KeyWords) {
            return base.Channel.SaveFltSlt1Async(operType, StrXML, TabName, KeyWords);
        }
        
        public void CloseSqlCon() {
            base.Channel.CloseSqlCon();
        }
        
        public System.Threading.Tasks.Task CloseSqlConAsync() {
            return base.Channel.CloseSqlConAsync();
        }
    }
}
